### ISSUE TITLE
Unable to deploy with SSH Key on dev-v4

### ISSUE THREAD

**Issue by JamesIves** [JamesIves/github-pages-deploy-action#586]
**Describe the bug**

Unable to deploy with an SSH key on `dev-v4` branch. This can be tested by running `releases/v4-beta`.

**Reproduce**

* Generate an ssh key: `ssh-keygen -t rsa -m pem -b 4096 -C "youremailhere@example.com" -N ""`
* Set the public key to the Deploy Tokens settings menu with write access.
* Set the private key as a secret and use the input `ssh-key` with the value.
* Deploy.

**Logs**

https://github.com/JamesIves/reddit-viewer/runs/1830742126?check_suite_focus=true

**Additional Comments**

Unsure why this stopped working, I'm guessing there's a command that isn't being initialized correctly.

**Comment by JamesIves** [comment]
This needs to be resolved before v4 releases, but debugging this issue is proving to be pretty difficult.

**Comment by Pike** [comment]
Can you test this on a public repo? Or put the logs on a gist or something?

**Comment by JamesIves** [comment]
Haha, my bad. I thought the repo was public:

```shell
Run JamesIves/github-pages-deploy-action@releases/v4-beta
  with:
    branch: gh-pages
    folder: build
    ssh-key: ***
    single-commit: true
    token: ***
    clean: true

    GitHub Pages Deploy Action 🚀

    🚀 Getting Started Guide: https://github.com/marketplace/actions/deploy-to-github-pages
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues

    📣 Maintained by James Ives: https://jamesiv.es
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and starting deployment… 🚦
Configuring SSH client… 🔑
/usr/bin/ssh-add - ***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
/usr/bin/ssh-add -l
Could not open a connection to your authentication agent.
Could not open a connection to your authentication agent.
(node:2477) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/ssh-add' failed with exit code 2
    at ExecState._setResult (/home/runner/work/_actions/JamesIves/github-pages-deploy-action/releases/v4-beta/node_modules/@actions/exec/lib/toolrunner.js:574:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/JamesIves/github-pages-deploy-action/releases/v4-beta/node_modules/@actions/exec/lib/toolrunner.js:557:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/JamesIves/github-pages-deploy-action/releases/v4-beta/node_modules/@actions/exec/lib/toolrunner.js:451:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
(node:2477) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2477) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: The ssh client configuration encountered an error: The process '/usr/bin/ssh-add' failed with exit code 2 ❌
Deployment failed! ❌
```

**Comment by Pike** [comment]
Seems you're missing to pull

```
SSH_AUTH_SOCK
SSH_AGENT_PID
```

from the output of `ssh-agent` into the process environment to be used by `ssh-add` and eventually `git`?

**Comment by JamesIves** [comment]
Ah yes, I'm not sure how this worked before...? At any rate I checked out some other ssh agent workflows and you're right, they all seem to do this. I've submitted a PR.
